M48
; DRILL file {KiCad 8.0.5} date 2025-04-26T14:00:16+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-26T14:00:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
%
G90
G05
T1
X3.096Y-4.627
X3.1526Y-4.6836
X3.3364Y-4.4432
T2
X2.2835Y-3.937
X3.937Y-3.937
M30
