CONFIG_NETWORKING=y

CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV6=y
CONFIG_NET_CONTEXT_RCVTIMEO=y
CONFIG_NET_CONTEXT_SNDTIMEO=y
CONFIG_COAP=y
CONFIG_DOWNLOADER=y
CONFIG_DOWNLOADER_TRANSPORT_COAP=y
CONFIG_FOTA_DOWNLOAD=y
